# Generated by Django 4.1.2 on 2022-10-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Researcher',
            fields=[
                ('co_researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('co_researcher_title', models.CharField(max_length=10)),
                ('co_researcher_firstname', models.CharField(max_length=255)),
                ('co_researcher_lastname', models.CharField(max_length=255)),
                ('co_researcher_email', models.CharField(max_length=255)),
                ('co_researcher_phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('funding_id', models.AutoField(primary_key=True, serialize=False)),
                ('funding_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Load_Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Research_Load',
            fields=[
                ('research_load_id', models.AutoField(primary_key=True, serialize=False)),
                ('research_topic', models.CharField(max_length=255)),
                ('research_load_description', models.CharField(max_length=255)),
                ('expected_research_time', models.IntegerField()),
                ('research_load_total_load_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co_researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_workload.co_researcher')),
                ('research_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_workload.load_status')),
                ('researching_funding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research_workload.funding')),
            ],
        ),
    ]
