# Generated by Django 4.1.2 on 2022-11-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('student_firstname', models.CharField(max_length=255)),
                ('student_lastname', models.CharField(max_length=255)),
                ('student_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.programme')),
            ],
        ),
    ]
