# Generated by Django 4.1.2 on 2022-11-07 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.IntegerField(unique=True, verbose_name='staff number')),
                ('staff_position', models.CharField(choices=[('Junior Lectuer', 'JUNIOR LECTURER'), ('Lecturer', 'LECTURER'), ('Senior Lecturer', 'SENIOR LECTURER'), ('Professor', 'PROFESSOR'), ('Associate Professor', 'ASSOCIATE PROFESSOR'), ('Dean', 'DEAN'), ('HoD', 'HEAD OF DEPARTMENT')], default='Lecturer', max_length=25)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
