# Generated by Django 4.1.2 on 2022-10-31 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWorkload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester')], max_length=20)),
                ('hours_per_semester', models.IntegerField()),
            ],
        ),
    ]
