# Generated by Django 4.1.2 on 2022-11-08 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
        ('community_workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityworkload',
            name='staff_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appauth.staff_member'),
        ),
    ]
