# Generated by Django 4.1.2 on 2022-11-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Group',
            fields=[
                ('course_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_group_name', models.CharField(max_length=255)),
                ('course_group_number', models.IntegerField()),
                ('course_group_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('programme_name', models.CharField(max_length=255)),
                ('programme_level', models.IntegerField()),
            ],
        ),
    ]
