# Generated by Django 4.1.2 on 2022-11-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching_Load',
            fields=[
                ('teaching_load_id', models.AutoField(primary_key=True, serialize=False)),
                ('novelty_of_course', models.CharField(choices=[('New to Course', 'NEW TO COURSE'), ('New to University', 'NEW TO UNIVERSITY'), ('Old to Course', 'OLD TO COURSE'), ('Old to University', 'OLD TO UNIVERSITY')], default='New to Course', max_length=255)),
                ('contact_time_per_week', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course_group')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.staff_member')),
            ],
        ),
        migrations.CreateModel(
            name='Honors_Supervision_Load',
            fields=[
                ('honors_supervision_load_id', models.AutoField(primary_key=True, serialize=False)),
                ('honors_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
