# Generated by Django 4.1.2 on 2022-10-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Group',
            fields=[
                ('course_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_group_name', models.CharField(max_length=255)),
                ('course_group_number', models.IntegerField()),
                ('course_group_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Honors_Supervision_Load',
            fields=[
                ('honors_supervision_load_id', models.AutoField(primary_key=True, serialize=False)),
                ('honors_student_number', models.IntegerField()),
                ('honors_student_firstname', models.CharField(max_length=255)),
                ('honors_student_lastname', models.CharField(max_length=255)),
                ('honors_student_program', models.CharField(max_length=255)),
                ('contact_time_per_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('novelty_id', models.AutoField(primary_key=True, serialize=False)),
                ('novelty_name', models.CharField(max_length=255)),
                ('novelty_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Teaching_Load',
            fields=[
                ('course_teaching_load_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=255)),
                ('novelty_of_course', models.CharField(max_length=255)),
                ('contact_time_per_week', models.IntegerField()),
                ('total_load_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching_workload.course_group')),
            ],
        ),
    ]
